package com.groupeisi.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CalendarAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarAllPropertiesEquals(Calendar expected, Calendar actual) {
        assertCalendarAutoGeneratedPropertiesEquals(expected, actual);
        assertCalendarAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarAllUpdatablePropertiesEquals(Calendar expected, Calendar actual) {
        assertCalendarUpdatableFieldsEquals(expected, actual);
        assertCalendarUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarAutoGeneratedPropertiesEquals(Calendar expected, Calendar actual) {
        assertThat(expected)
            .as("Verify Calendar auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarUpdatableFieldsEquals(Calendar expected, Calendar actual) {
        assertThat(expected)
            .as("Verify Calendar relevant properties")
            .satisfies(e -> assertThat(e.getDate()).as("check date").isEqualTo(actual.getDate()))
            .satisfies(e -> assertThat(e.getDayofweek()).as("check dayofweek").isEqualTo(actual.getDayofweek()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarUpdatableRelationshipsEquals(Calendar expected, Calendar actual) {}
}
